### ISSUE TITLE
please I need your help for doing some integrations

### ISSUE THREAD

**Issue by divbhalala** [SanichKotikov/react-family-tree#10]
Please check this https://codesandbox.io/s/weevusissue-uvuk0?file=/src/components/App/App.tsx:2127-2173. I created tree in test-tree-n1.JSON and I want you to give some help for implementing like screenshot added below

Here is JSON data `[
  {
    id: "me",
    gender: "male",
    spouses: [],
    siblings: [],
    parents: [
      { id: "father", type: "blood" },
      { id: "mother", type: "blood" }
    ],
    children: []
  },
  {
    id: "father",
    gender: "male",
    spouses: [{ id: "mother", type: "married" }],
    siblings: [{ id: "fa_brother", type: "blood" }],
    parents: [
      { id: "fa_Pa", type: "blood" },
      { id: "fa_Ma", type: "blood" }
    ],
    children: [{ id: "me", type: "blood" }]
  },
  {
    id: "mother",
    gender: "female",
    spouses: [{ id: "father", type: "married" }],
    siblings: [],
    parents: [
      { id: "gg_Pa", type: "blood" },
      { id: "gg_Ma", type: "blood" }
    ],
    children: [{ id: "me", type: "blood" }]
  },
  {
    id: "gg_Pa",
    gender: "male",
    spouses: [{ id: "gg_Ma", type: "married" }],
    siblings: [],
    parents: [],
    children: [{ id: "mother", type: "blood" }]
  },
  {
    id: "gg_Ma",
    gender: "female",
    spouses: [{ id: "gg_Pa", type: "married" }],
    siblings: [],
    parents: [],
    children: [{ id: "mother", type: "blood" }]
  },
  {
    id: "fa_brother",
    gender: "male",
    spouses: [{ id: "fa_bro_spo", type: "married" }],
    siblings: [{ id: "father", type: "blood" }],
    parents: [
      { id: "fa_Pa", type: "blood" },
      { id: "fa_Ma", type: "blood" }
    ],
    children: []
  },
  {
    id: "fa_bro_spo",
    gender: "male",
    spouses: [{ id: "fa_brother", type: "married" }],
    siblings: [],
    parents: [],
    children: []
  },
  {
    id: "fa_Pa",
    gender: "male",
    spouses: [{ id: "fa_Ma", type: "blood" }],
    siblings: [],
    parents: [],
    children: [
      { id: "father", type: "blood" },
      { id: "fa_brother", type: "blood" }
    ]
  },
  {
    id: "fa_Ma",
    gender: "female",
    spouses: [{ id: "fa_Pa", type: "blood" }],
    siblings: [],
    parents: [],
    children: [
      { id: "father", type: "blood" },
      { id: "fa_brother", type: "blood" }
    ]
  }
]`

In this screenshot you can see that node is not displaying

![image (3)](https://user-images.githubusercontent.com/90197187/134354229-a38a3924-b293-44c6-8461-0711db6b5f4f.png)

I need to display that node when this particular node is selected whichYou can see that in screenshot below

![image (4)](https://user-images.githubusercontent.com/90197187/134355399-eee092e0-484d-484d-8a12-7d9de9b2139f.png)

**Comment by SanichKotikov** [comment]
Stop spamming.
