### ISSUE TITLE
Family Tree Nodes are not being translated

### ISSUE THREAD

**Issue by miraabela** [SanichKotikov/react-family-tree#12]
![image](https://user-images.githubusercontent.com/26056985/145318683-6634caa7-c2fd-43f5-b65b-90e64bf1984d.png)

Hi there, first of all thank you so much for this library. I tried using your library and this is what results. The connectors are showing up but the Cards are not being moved to where it is supposed to be. If you want to look at my code it is at

Not sure what to do, would you be able to help me? Thanks so much

**Comment by fcsonline** [comment]
Maybe it is a CSS problem. Check if you are positioning correctly with `position: absolute` in the parent of those FamilyNode
