### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by estyxx** [SanichKotikov/react-family-tree#13]
This library seems very nice! I would like to have a try with this but I got this error and I can't able to figure out what is happening here... 

I just created a sample clean repo [here](https://github.com/estyxx/family-tree)

I'm using  node v16.11.1

Hope that helps :)

**Comment by taofik-adeniyi** [comment]
having same error where you able to find a fix for it @estyxx

**Comment by SanichKotikov** [comment]
See https://github.com/SanichKotikov/react-family-tree/issues/15
