### ISSUE TITLE
Throws Error when used in nextjs

### ISSUE THREAD

**Issue by taofik-adeniyi** [SanichKotikov/react-family-tree#15]
Server Error
SyntaxError: Cannot use import statement outside a module
module.exports = require("react-family-tree");

**Comment by SanichKotikov** [comment]
It's an issue of your bundling configuration, not the library.
Note: the lib uses es6 import/export syntax.

**Comment by taofik-adeniyi** [comment]
i am using nextjs please how can i fix this @SanichKotikov
