### ISSUE TITLE
Can't click detail on mobile

### ISSUE THREAD

**Issue by mhdramadhanarvin** [SanichKotikov/react-family-tree#20]
I am using this package for my family tree, but when I access from mobile, I can't click to see the details, I think there is a problem in my code, but when I access your demo at url https://sanichkotikov.github.io/react-family-tree-example, I can't see the details on mobile either.

**Comment by SanichKotikov** [comment]
It might be a bug in https://github.com/SanichKotikov/pinch-zoom-pan
I'll check it later.

**Comment by mhdramadhanarvin** [comment]
I hope the bug can be fixed as soon as possible

**Comment by SanichKotikov** [comment]
Should be fixed in `pinch-zoom-pan` `v4.0.2`.
Also updated https://github.com/SanichKotikov/react-family-tree-example
