### ISSUE TITLE
Child with unmarried parents not rendering

### ISSUE THREAD

**Issue by kabelo2ka** [SanichKotikov/react-family-tree#24]
When the child has unmarried parents, but one of the parent has a spouse, the child node does not render when the parent with the spouse is `rootId`. How can we fix that please?

**Comment by SanichKotikov** [comment]
Hi. Please, provide an example json data.

**Comment by SanichKotikov** [comment]
I'll close this issue for now. If you still need help, provide an example json data and reopen issue.
