### ISSUE TITLE
Broken position

### ISSUE THREAD

**Issue by pravosleva** [SanichKotikov/react-family-tree#25]
![photo_2024-07-10_10-09-31](https://github.com/SanichKotikov/react-family-tree/assets/19761493/7bc4e3a7-79f1-4b9e-9490-e31bd400ec4e)

**Comment by SanichKotikov** [comment]
Please, provide json file with the issue.

**Comment by pravosleva** [comment]
> Please, provide json file with the issue.

Take it [here](https://pravosleva.pro/express-helper/subprojects/exp.family/pravosleva?v=temporal&target=lyuba-vladimir-garbuzova.[28-04-1976])

**Comment by SanichKotikov** [comment]
Fixed in relatives-tree v3.2.1
