### ISSUE TITLE
Displaying uncle during Child as root node

### ISSUE THREAD

**Issue by divbhalala** [SanichKotikov/react-family-tree#8]
During child as root node It is not displaying uncle node. It is only shows parents.
You can see it in below screenshot

https://prnt.sc/1re8zez

**Comment by divsbhalala** [comment]
![image](https://user-images.githubusercontent.com/12185309/133408206-cda0ab9e-01bf-4c17-a781-6a4baf03fd15.png)

**Comment by SanichKotikov** [comment]
The library does not support uncles or any other relation except parents in parent direction.

**Comment by savissimo** [comment]
What would you need to enable this feature? I am willing to help, but I may need pointers.

**Comment by SanichKotikov** [comment]
> What would you need to enable this feature? I am willing to help, but I may need pointers.

I see only one option: show an uncle/aunt without other child or parent connections, and only for root node.
