### ISSUE TITLE
I want to display uncle node when child-node is at root

### ISSUE THREAD

**Issue by divbhalala** [SanichKotikov/react-family-tree#9]
Please check this https://codesandbox.io/s/weevusissue-uvuk0 and select uncle-issue.json. I want you to help me in this issue.

Here is provided JSON data

`[
  {
    id: "0chil",
    gender: "male",
    spouses: [],
    siblings: [],
    parents: [{ id: "1fath", type: "blood" }],
    children: []
  },
  {
    id: "1fath",
    gender: "male",
    spouses: [],
    siblings: [{ id: "uncle", type: "blood" }],
    parents: [
      { id: "grandPa", type: "blood" },
      { id: "grandMa", type: "blood" }
    ],
    children: [{ id: "0chil", type: "blood" }]
  },
  {
    id: "uncle",
    gender: "male",
    spouses: [],
    siblings: [{ id: "1fath", type: "blood" }],
    parents: [
      { id: "grandPa", type: "blood" },
      { id: "grandMa", type: "blood" }
    ],
    children: []
  },
  {
    id: "grandPa",
    gender: "male",
    spouses: [],
    siblings: [],
    parents: [],
    children: [
      { id: "1fath", type: "blood" },
      { id: "uncle", type: "blood" }
    ]
  },
  {
    id: "grandMa",
    gender: "male",
    spouses: [],
    siblings: [],
    parents: [],
    children: [
      { id: "1fath", type: "blood" },
      { id: "uncle", type: "blood" }
    ]
  }
]`
![image (1)](https://user-images.githubusercontent.com/90197187/134144504-2d93af4e-3b1a-4b75-bc46-5693179a0ce2.png)

**Comment by SanichKotikov** [comment]
Duplicate https://github.com/SanichKotikov/react-family-tree/issues/8
